
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.demo.sample.abhishek.io
  labels:
    api: sample-aggregated-api
    apiserver: "true"
spec:
  version: v1alpha1
  group: demo.sample.abhishek.io
  groupPriorityMinimum: 2000
  service:
    name: sample-aggregated-api
    namespace: person
  versionPriority: 10
  caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR6akNDQXJhZ0F3SUJBZ0lVVHBYTVpUeW1uWjV2TkRaeWNNUGR3WkQrWFE4d0RRWUpLb1pJaHZjTkFRRUwKQlFBd2RURUxNQWtHQTFVRUJoTUNkVzR4Q3pBSkJnTlZCQWdNQW5OME1Rb3dDQVlEVlFRSERBRnNNUW93Q0FZRApWUVFLREFGdk1Rc3dDUVlEVlFRTERBSnZkVEUwTURJR0ExVUVBd3dyYzJGdGNHeGxMV0ZuWjNKbFoyRjBaV1F0CllYQnBMV05sY25ScFptbGpZWFJsTFdGMWRHaHZjbWwwZVRBZUZ3MHlNakE1TURneE5EUTRNRFJhRncweU16QTUKTURneE5EUTRNRFJhTUhVeEN6QUpCZ05WQkFZVEFuVnVNUXN3Q1FZRFZRUUlEQUp6ZERFS01BZ0dBMVVFQnd3QgpiREVLTUFnR0ExVUVDZ3dCYnpFTE1Ba0dBMVVFQ3d3Q2IzVXhOREF5QmdOVkJBTU1LM05oYlhCc1pTMWhaMmR5ClpXZGhkR1ZrTFdGd2FTMWpaWEowYVdacFkyRjBaUzFoZFhSb2IzSnBkSGt3Z2dFaU1BMEdDU3FHU0liM0RRRUIKQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUNqRlpyWWN1MFU1OStyVkk3dVZBMU1TcGI5TmVqbWIwYUNPYXNZYm5ueApBbmNiaFVYbUtjSU5tc0xRcmtxOEw4Zks5dUphcGJSekdrYUxOTi9JcW5jRFpWMWZBVHY2dENFcUMrMUlxRVFvCnpjbGtpRW1FNzVLbU01MHpMRGtDRUVob1U4S1h3OGVUVWxxeE9DWXBlSUJaNjQzbXhwZTJjV3ZXMURzRFlFYzMKK2NUclJKQzNZUVZHY0hFelFBRjRGUGUrM3FlaDgwNFJTamZ3djhlcTJraXpYOEtDL1JISWx2ZFZGZXZFd2FDWgpMcGRzYXRGMkd4Um1uVXNORDV1eGIwanhuQU1jbUZPWjF4aTJVVElWLzlRekNWVG9YSnlrNU5VS0crd0hKcGFKCnlKbnNnL29WelBBVGM3YUw2T1FjcU1pL0laTGorZnpHR2hjNTk0VDBWRHE5QWdNQkFBR2pWakJVTUIwR0ExVWQKRGdRV0JCVGI0VWJtbTZhUTBrWWJkQ3drTWlLU1JzVUYxREFmQmdOVkhTTUVHREFXZ0JUYjRVYm1tNmFRMGtZYgpkQ3drTWlLU1JzVUYxREFTQmdOVkhSTUJBZjhFQ0RBR0FRSC9BZ0VCTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCCkFRQ1owTjhOYlhJalVKbWE4Qjl2dXczdFA3SDk2dGNrSkRWUXh2ZjU3ZVpDa1l0UmdkMGlEeUpBYk1xYnIvV2IKNFlzeWRQTVhJNkxEOFAwZmN4dTRYV0NIdXF6V0FFV3BiU29ES2lTY1doQ0dQeTkxQnhRaExrMG1RS0d2ZW1kagpBZ21qZ2pGUmYzMW5JYTBaZjV6ZjVvSk9QUDg0VmtGZStLdjVSYjJqRUx3VWlPZEhZR1BFMG9kWWlVakZibVN1CnhtNHhrZEQxK3RiZHBBd1hFQTZrRXYwRURlZkp1TmFXMHBKMjd5NUlycVRDY0JHMi96ZHZlU0ZxcnJncU1NZ1EKUHYvMkd4eGpka1ZmakZPczhCOUFab0JEMDZUbldQcXZkMUpjNEJmMUNTWGxFVUpBS2hWYjQvKzdaaXpJanhMcgo1MTBENU1uZnRJR0w2TzdsSHh2RE9sTVAKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
---
